using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace VRCore.Editor.Modules.FolderStructure
{
    public static class VRFolderStructureGenerator
    {
        public static (int createdCount, int existedCount, string rootPath) Generate(
            List<VRFolderItem> folderItems,
            string rootPrefix,
            bool createGitKeep,
            bool createReadme)
        {
            int createdCount = 0;
            int existedCount = 0;

            string baseAssetsPath = Application.dataPath; // Absolute path to Assets/
            string projectRootRelative = "Assets";

            if (!string.IsNullOrWhiteSpace(rootPrefix))
            {
                // Clean prefix
                string cleanPrefix = rootPrefix.Trim().TrimStart('/', '\\').TrimEnd('/', '\\');
                projectRootRelative = $"Assets/{cleanPrefix}";
                string absoluteRoot = Path.Combine(baseAssetsPath, cleanPrefix);

                if (!Directory.Exists(absoluteRoot))
                {
                    Directory.CreateDirectory(absoluteRoot);
                    createdCount++;
                }
            }

            foreach (var item in folderItems)
            {
                if (!item.IsEnabled || string.IsNullOrWhiteSpace(item.RelativePath)) continue;

                string cleanRelative = item.RelativePath.Trim().TrimStart('/', '\\');
                string targetRelativePath = $"{projectRootRelative}/{cleanRelative}";
                string targetAbsolutePath = Path.Combine(Application.dataPath, targetRelativePath.Substring("Assets/".Length));

                if (Directory.Exists(targetAbsolutePath))
                {
                    existedCount++;
                }
                else
                {
                    Directory.CreateDirectory(targetAbsolutePath);
                    createdCount++;

                    if (createGitKeep)
                    {
                        string gitKeepPath = Path.Combine(targetAbsolutePath, ".gitkeep");
                        if (!File.Exists(gitKeepPath))
                        {
                            File.WriteAllText(gitKeepPath, "");
                        }
                    }
                }
            }

            if (createReadme)
            {
                CreateProjectReadme(projectRootRelative, folderItems);
            }

            AssetDatabase.Refresh();
            return (createdCount, existedCount, projectRootRelative);
        }

        private static void CreateProjectReadme(string projectRootRelative, List<VRFolderItem> folderItems)
        {
            string rootAbsolute = projectRootRelative == "Assets" 
                ? Application.dataPath 
                : Path.Combine(Application.dataPath, projectRootRelative.Substring("Assets/".Length));

            string readmePath = Path.Combine(rootAbsolute, "PROJECT_STRUCTURE.md");
            if (File.Exists(readmePath)) return; // Do not overwrite existing docs

            var sb = new System.Text.StringBuilder();
            sb.AppendLine("# VR Project Architecture & Folder Guide");
            sb.AppendLine();
            sb.AppendLine($"Generated by **VR Central Hub** on {DateTime.Now:yyyy-MM-dd HH:mm}.");
            sb.AppendLine();
            sb.AppendLine("## Folder Structure Overview");
            sb.AppendLine();

            string currentCategory = "";
            foreach (var item in folderItems)
            {
                if (!item.IsEnabled) continue;

                if (item.Category != currentCategory)
                {
                    currentCategory = item.Category;
                    sb.AppendLine($"### {currentCategory}");
                }
                sb.AppendLine($"- **`{item.RelativePath}`**: {item.Description}");
            }

            sb.AppendLine();
            sb.AppendLine("## Developer Guidelines");
            sb.AppendLine("- Keep third-party plugins in `Assets/Plugins` or Package Manager.");
            sb.AppendLine("- Custom game assets should strictly reside inside their designated subfolders.");
            sb.AppendLine("- Maintain scene test sandboxes in `Scenes/Sandbox` before promoting to `Scenes/Main`.");

            try
            {
                File.WriteAllText(readmePath, sb.ToString());
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[VR Central Hub] Could not create PROJECT_STRUCTURE.md: {ex.Message}");
            }
        }
    }
}
